const lessons = [
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Введение', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Простой учебник', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Общие инструкции по установке', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка на Unix-системы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка на macOS', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка в системах Windows', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка на платформах Cloud Computing', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Менеджер процессов FastCGI (FPM)', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка модулей PECL', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Проблемы?', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Конфигурация времени выполнения', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Основы синтаксиса', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Типы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Переменные', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Константы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Выражения', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Операторы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Управляющие конструкции', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Функции', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Классы и объекты', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Пространства имён', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Перечисления', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Ошибки', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Исключения', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Fibers', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Генераторы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Атрибуты', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Объяснение ссылок', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Предопределённые переменные', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Предопределённые исключения', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Встроенные интерфейсы и классы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Предопределённые атрибуты', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Опции и параметры контекста', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Протоколы и обёртки', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Вступление', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Общие соображения', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Если PHP установлен как CGI', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Если PHP установлен как модуль Apache', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Безопасность сессий', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Безопасность файловой системы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Безопасность баз данных', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Сообщения об ошибках', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Данные, введённые пользователем', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Сокрытие PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Необходимость обновлений', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'HTTP-аутентификация в PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Cookies', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Сессии', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Загрузка файлов на сервер', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Работа с удалёнными файлами', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Работа с соединениями', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Постоянные соединения с базами данных', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Работа с PHP из командной строки', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Сборка мусора', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Динамическая трассировка DTrace', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Изменение поведения PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Обработка аудиоформатов', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Службы аутентификации', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с командной строкой', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для сжатия и архивации', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Криптографические модули', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с базами данных', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с датой и временем', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с файловой системой', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Поддержка языков и кодировок', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Обработка и генерация изображений', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с почтой', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Математические модули', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Генерация нетекстовых MIME-форматов', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для управления процессами программ', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Другие базовые модули', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Другие службы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с поисковыми системами', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с серверами', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с сессиями', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Обработка текста', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с переменными и типами', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Веб-сервисы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули только для Windows', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Обработка XML', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Модули для работы с GUI', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Общая информация', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Списки рассылки', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Получение PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Вопросы по базам данных — Вопросы по Базам данных', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Установка', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Проблемы сборки', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Использование PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Хеширование паролей — Безопасное хеширование паролей', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'PHP и HTML — PHP и HTML-разметка', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'PHP и COM', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Разные вопросы', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'История PHP и смежных проектов', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 8.2.x на PHP 8.3.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 8.1.x на PHP 8.2.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 8.0.x на PHP 8.1.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 7.4.x на PHP 8.0.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 7.3.x на PHP 7.4.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 7.2.x на PHP 7.3.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 7.1.x на PHP 7.2.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 7.0.x на PHP 7.1.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 5.6.x на PHP 7.0.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Миграция с PHP 5.5.x на PHP 5.6.x', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Отладка в PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Опции конфигурации', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Директивы php.ini', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список и классификация модулей', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список псевдонимов функций', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список зарезервированных слов', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список типов ресурсов', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список доступных фильтров', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список транспортных протоколов для работы с сокетами', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Таблицы сравнения типов PHP', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список меток (tokens) парсера', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Руководство по именованию', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'О руководстве', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Creative Commons Attribution 3.0', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Алфавитный список', status: 'in_progress' },
    { title: 'PHP https://www.php.net/manual/ru/', content: 'Список изменений', status: 'in_progress' },


    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Release Notes', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Upgrade Guide', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Contribution Guide', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Installation', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Configuration', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Directory Structure', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Frontend', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Starter Kits', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Deployment', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Request Lifecycle', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Service Container', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Service Providers', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Facades', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Routing', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Middleware', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'CSRF Protection', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Controllers', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Requests', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Responses', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Views', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Blade Templates', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Asset Bundling', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'URL Generation', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Session', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Validation', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Error Handling', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Logging', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Artisan Console', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Broadcasting', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Cache', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Collections', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Context', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Contracts', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Events', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'File Storage', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Helpers', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'HTTP Client', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Localization', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Mail', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Notifications', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Package Development', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Processes', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Queues', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Rate Limiting', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Strings', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Task Scheduling', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Authentication', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Authorization', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Email Verification', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Encryption', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Hashing', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Password Reset', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Getting Started (Query Builder)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Pagination', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Migrations', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Seeding', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Redis', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Getting Started (Relationships)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Collections (Relationships)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Mutators / Casts', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'API Resources', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Serialization', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Factories', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Getting Started (HTTP Tests)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Console Tests', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Browser Tests', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Database Mocking', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Breeze', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Cashier (Stripe)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Cashier (Paddle)', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Dusk', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Envoy', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Fortify', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Folio', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Homestead', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Horizon', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Jetstream', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Mix', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Octane', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Passport', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Pennant', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Pint', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Precognition', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Prompts', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Pulse', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Reverb', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Sail', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Sanctum', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Scout', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Socialite', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Telescope', status: 'in_progress' },
    { title: 'Laravel https://laravel.com/docs/11.x/readme', content: 'Valet', status: 'in_progress' },






    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'About this documentation', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Usage and example', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Assertion testing', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Asynchronous context tracking', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Async hooks', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Buffer', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'C++ addons', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'C/C++ addons with Node-API', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'C++ embedder API', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Child processes', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Cluster', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Command-line options', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Console', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Corepack', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Crypto', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Debugger', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Deprecated APIs', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Diagnostics Channel', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'DNS', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Domain', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Errors', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Events', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'File system', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Globals', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'HTTP', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'HTTP/2', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'HTTPS', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Inspector', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Internationalization', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Modules: CommonJS modules', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Modules: ECMAScript modules', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Modules: node:module API', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Modules: Packages', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Modules: TypeScript', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Net', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'OS', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Path', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Performance hooks', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Permissions', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Process', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Punycode', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Query strings', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Readline', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'REPL', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Report', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Single executable applications', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'SQLite', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Stream', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'String decoder', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Test runner', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Timers', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'TLS/SSL', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Trace events', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'TTY', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'UDP/datagram', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'URL', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Utilities', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'V8', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'VM', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'WASI', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Web Crypto API', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Web Streams API', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Worker threads', status: 'in_progress' },
    { title: 'Node JS https://nodejs.org/docs/latest/api/', content: 'Zlib', status: 'in_progress' },


















    { title: 'Nest JS https://docs.nestjs.com/', content: 'First steps', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Controllers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Providers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Modules', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Middleware', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Exception filters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Pipes', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Guards', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Interceptors', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Custom decorators', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Custom providers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Asynchronous providers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Dynamic modules', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Injection scopes', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Circular dependency', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Module reference', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Lazy-loading modules', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Execution context', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Lifecycle events', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Platform agnosticism', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Testing', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Configuration', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Database', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Mongo', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Validation', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Caching', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Serialization', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Versioning', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Task scheduling', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Queues', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Logging', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Cookies', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Events', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Compression', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'File upload', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Streaming files', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'HTTP module', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Session', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Model-View-Controller', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Performance (Fastify)', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Server-Sent Events', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Authentication', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Authorization', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Encryption and Hashing', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Helmet', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CSRF Protection', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Rate limiting', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Quick start', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Resolvers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Mutations', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Subscriptions', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Scalars', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Directives', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Interfaces', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Unions and Enums', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Field middleware', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Mapped types', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Plugins', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Complexity', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Extensions', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CLI Plugin', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Generating SDL', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Sharing models', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Other features', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Federation', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Migration guide', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Gateways', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Exception filters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Pipes', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Guards', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Interceptors', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Adapters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Overview', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Redis', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'MQTT', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'RabbitMQ', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Kafka', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'gRPC', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Custom transporters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Exception filters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Pipes', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Guards', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Interceptors', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'STANDALONE APPS', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Overview', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Workspaces', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Libraries', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Usage', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Scripts', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Introduction', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Types and Parameters', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Operations', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Security', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Mapped Types', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Decorators', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CLI Plugin', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Other features', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Migration guide', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'RECIPES', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CRUD generator', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'SWC (fast compiler)', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Passport (auth)', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Hot reload', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'MikroORM', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'TypeORM', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Mongoose', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Sequelize', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Router module', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Swagger', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Health checks', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CQRS', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Compodoc', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Prisma', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Serve static', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Commander', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Async local storage', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Automock', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Serverless', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'HTTP adapter', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Keep-Alive connections', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Global path prefix', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Raw body', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Hybrid application', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'HTTPS & multiple servers', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Request lifecycle', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Common errors', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Examples', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'Overview', status: 'in_progress' },
    { title: 'Nest JS https://docs.nestjs.com/', content: 'CI/CD integration', status: 'in_progress' },






    { title: 'GO https://go.dev/doc/', content: 'Installing Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Getting started', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Create a module', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Getting started with multi-module workspaces', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Developing a RESTful API with Go and Gin', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Getting started with generics', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Getting started with fuzzing', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Writing Web Applications', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'How to write Go code', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'A Tour of Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Effective Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Frequently Asked Questions (FAQ)', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Editor plugins and IDEs', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Diagnostics', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'A Guide to the Go Garbage Collector', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Managing dependencies', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Fuzzing', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Coverage for Go applications', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Profile-guided optimization', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Package Documentation', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Command Documentation', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Language Specification', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Modules Reference', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'go.mod file reference', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'The Go Memory Model', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Contribution Guide', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Release History', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Tutorial: Accessing a relational database', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Accessing relational databases', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Opening a database handle', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Executing SQL statements that don\'t return data', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Querying for data', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Using prepared statements', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Executing transactions', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Canceling in-progress database operations', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Managing connections', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Avoiding SQL injection risk', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Developing and publishing modules', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Module release and versioning workflow', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Managing module source', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Organizing a Go module', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Developing a major version update', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Publishing a module', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Module version numbering', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'A Video Tour of Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Code that grows with grace', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Concurrency Patterns', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Advanced Go Concurrency Patterns', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'First-Class Functions in Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Generating arbitrary text: a Markov chain algorithm', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Share Memory by Communicating', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'JSON-RPC: a tale of interfaces', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go\'s Declaration Syntax', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Defer, Panic, and Recover', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Concurrency Patterns: Timing out, moving on', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Slices: usage and internals', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'A GIF decoder: an exercise in Go interfaces', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Error Handling and Go', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'JSON and Go - using the json package.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Gobs of data - the design and use of the gob package.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'The Laws of Reflection - the fundamentals of the reflect package.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'The Go image package - the fundamentals of the image package.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'The Go image/draw package - the fundamentals of the image/draw package.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Using Go Modules - an introduction to using modules in a simple project.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Migrating to Go Modules - converting an existing project to use modules.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Publishing Go Modules - how to make new versions of modules available to others.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Modules: v2 and Beyond - creating and publishing major versions 2 and higher.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Keeping Your Modules Compatible - how to keep your modules compatible with prior minor/patch versions.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'About the Go command - why we wrote it, what it is, what it\'s not, and how to use it.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Go Doc Comments - writing good program documentation', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Debugging Go Code with GDB', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Data Race Detector - a manual for the data race detector.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'A Quick Guide to Go\'s Assembler - an introduction to the assembler used by Go.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'C? Go? Cgo! - linking against C code with cgo.', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Profiling Go Programs', status: 'in_progress' },
    { title: 'GO https://go.dev/doc/', content: 'Introducing the Go Race Detector - an introduction to the race detector.', status: 'in_progress' },




    { title: 'Спорт', content: 'Отжимания от пола', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Мостик для ягодиц', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с узким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на пресс', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с широким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Болгарские выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с выпадами', status: 'in_progress' },
    { title: 'Спорт', content: 'Бёрпи', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы ног в висе', status: 'in_progress' },
    { title: 'Спорт', content: 'Боковая планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на месте', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на одной руке', status: 'in_progress' },
    { title: 'Спорт', content: 'Пистолет (приседания на одной ноге)', status: 'in_progress' },
    { title: 'Спорт', content: 'Скалолаз', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с хлопком', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса (кранчи)', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпрыгивания из приседа', status: 'in_progress' },
    { title: 'Спорт', content: 'Разгибания корпуса (супермен)', status: 'in_progress' },
    { title: 'Спорт', content: 'Лодочка', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы коленей в прыжке', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Плие-приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Джампинг джек', status: 'in_progress' },
    { title: 'Спорт', content: 'Круговые махи ногами', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные скручивания', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на колени', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в приседе', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса с поворотом', status: 'in_progress' },
    { title: 'Спорт', content: 'Русский твист', status: 'in_progress' },
    { title: 'Спорт', content: 'Вращения корпуса', status: 'in_progress' },
    { title: 'Спорт', content: 'Косые выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с прыжком', status: 'in_progress' },
    { title: 'Спорт', content: 'Голень вверх (подъемы на носки)', status: 'in_progress' },
    { title: 'Спорт', content: 'Реверсивные выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на одну руку', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушачий прыжок', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания сумо', status: 'in_progress' },
    { title: 'Спорт', content: 'Звездные прыжки', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы рук в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Бег на месте с высокими коленями', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на пальцах', status: 'in_progress' },
    { title: 'Спорт', content: 'Супермен с отжиманием', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с подъемом ноги', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушки (прыжок вперед)', status: 'in_progress' },
    { title: 'Спорт', content: 'Уголок на полу', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальный бег в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания с подъемом ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Махи ногами вперед', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на косые мышцы', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги с отжиманиями', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с разведением ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с вращением', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка с подъемом ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания от пола', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Мостик для ягодиц', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с узким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на пресс', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с широким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Болгарские выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с выпадами', status: 'in_progress' },
    { title: 'Спорт', content: 'Бёрпи', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы ног в висе', status: 'in_progress' },
    { title: 'Спорт', content: 'Боковая планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на месте', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на одной руке', status: 'in_progress' },
    { title: 'Спорт', content: 'Пистолет (приседания на одной ноге)', status: 'in_progress' },
    { title: 'Спорт', content: 'Скалолаз', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с хлопком', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса (кранчи)', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпрыгивания из приседа', status: 'in_progress' },
    { title: 'Спорт', content: 'Разгибания корпуса (супермен)', status: 'in_progress' },
    { title: 'Спорт', content: 'Лодочка', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы коленей в прыжке', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Плие-приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Джампинг джек', status: 'in_progress' },
    { title: 'Спорт', content: 'Круговые махи ногами', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные скручивания', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на колени', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в приседе', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса с поворотом', status: 'in_progress' },
    { title: 'Спорт', content: 'Русский твист', status: 'in_progress' },
    { title: 'Спорт', content: 'Вращения корпуса', status: 'in_progress' },
    { title: 'Спорт', content: 'Косые выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с прыжком', status: 'in_progress' },
    { title: 'Спорт', content: 'Голень вверх (подъемы на носки)', status: 'in_progress' },
    { title: 'Спорт', content: 'Реверсивные выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на одну руку', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушачий прыжок', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания сумо', status: 'in_progress' },
    { title: 'Спорт', content: 'Звездные прыжки', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы рук в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Бег на месте с высокими коленями', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на пальцах', status: 'in_progress' },
    { title: 'Спорт', content: 'Супермен с отжиманием', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с подъемом ноги', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушки (прыжок вперед)', status: 'in_progress' },
    { title: 'Спорт', content: 'Уголок на полу', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальный бег в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания с подъемом ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Махи ногами вперед', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на косые мышцы', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги с отжиманиями', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с разведением ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с вращением', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка с подъемом ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания от пола', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Мостик для ягодиц', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с узким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на пресс', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с широким хватом', status: 'in_progress' },
    { title: 'Спорт', content: 'Болгарские выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с выпадами', status: 'in_progress' },
    { title: 'Спорт', content: 'Бёрпи', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы ног в висе', status: 'in_progress' },
    { title: 'Спорт', content: 'Боковая планка', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на месте', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на одной руке', status: 'in_progress' },
    { title: 'Спорт', content: 'Пистолет (приседания на одной ноге)', status: 'in_progress' },
    { title: 'Спорт', content: 'Скалолаз', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с хлопком', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса (кранчи)', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Выпрыгивания из приседа', status: 'in_progress' },
    { title: 'Спорт', content: 'Разгибания корпуса (супермен)', status: 'in_progress' },
    { title: 'Спорт', content: 'Лодочка', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы коленей в прыжке', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные отжимания', status: 'in_progress' },
    { title: 'Спорт', content: 'Плие-приседания', status: 'in_progress' },
    { title: 'Спорт', content: 'Джампинг джек', status: 'in_progress' },
    { title: 'Спорт', content: 'Круговые махи ногами', status: 'in_progress' },
    { title: 'Спорт', content: 'Обратные скручивания', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на колени', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги в приседе', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы корпуса с поворотом', status: 'in_progress' },
    { title: 'Спорт', content: 'Русский твист', status: 'in_progress' },
    { title: 'Спорт', content: 'Вращения корпуса', status: 'in_progress' },
    { title: 'Спорт', content: 'Косые выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с прыжком', status: 'in_progress' },
    { title: 'Спорт', content: 'Голень вверх (подъемы на носки)', status: 'in_progress' },
    { title: 'Спорт', content: 'Реверсивные выпады', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с опорой на одну руку', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушачий прыжок', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания сумо', status: 'in_progress' },
    { title: 'Спорт', content: 'Звездные прыжки', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъемы рук в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Бег на месте с высокими коленями', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания на пальцах', status: 'in_progress' },
    { title: 'Спорт', content: 'Супермен с отжиманием', status: 'in_progress' },
    { title: 'Спорт', content: 'Приседания с подъемом ноги', status: 'in_progress' },
    { title: 'Спорт', content: 'Лягушки (прыжок вперед)', status: 'in_progress' },
    { title: 'Спорт', content: 'Уголок на полу', status: 'in_progress' },
    { title: 'Спорт', content: 'Горизонтальный бег в планке', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания с подъемом ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Махи ногами вперед', status: 'in_progress' },
    { title: 'Спорт', content: 'Подъем таза на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Скручивания на косые мышцы', status: 'in_progress' },
    { title: 'Спорт', content: 'Шаги с отжиманиями', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки с разведением ног', status: 'in_progress' },
    { title: 'Спорт', content: 'Отжимания с вращением', status: 'in_progress' },
    { title: 'Спорт', content: 'Прыжки на одной ноге', status: 'in_progress' },
    { title: 'Спорт', content: 'Планка с подъемом ног', status: 'in_progress' },



    { title: 'Алгебра', content: 'Основы арифметики: натуральные числа и операции', status: 'in_progress' },
    { title: 'Алгебра', content: 'Делимость и простые числа', status: 'in_progress' },
    { title: 'Алгебра', content: 'Дроби и проценты', status: 'in_progress' },
    { title: 'Алгебра', content: 'Рациональные числа: сложение, вычитание, умножение, деление', status: 'in_progress' },
    { title: 'Алгебра', content: 'Основы уравнений: решение простых уравнений', status: 'in_progress' },
    { title: 'Алгебра', content: 'Линейные уравнения с одной переменной', status: 'in_progress' },
    { title: 'Алгебра', content: 'Линейные неравенства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Системы линейных уравнений (графический метод)', status: 'in_progress' },
    { title: 'Алгебра', content: 'Многочлены: сложение, вычитание, умножение', status: 'in_progress' },
    { title: 'Алгебра', content: 'Формулы сокращенного умножения', status: 'in_progress' },
    { title: 'Алгебра', content: 'Квадратные уравнения: нахождение корней', status: 'in_progress' },
    { title: 'Алгебра', content: 'Системы линейных уравнений (метод подстановки и исключения)', status: 'in_progress' },
    { title: 'Алгебра', content: 'Рациональные дроби и их свойства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Прогрессии: арифметическая и геометрическая', status: 'in_progress' },
    { title: 'Алгебра', content: 'Основы функции: понятие и график', status: 'in_progress' },
    { title: 'Алгебра', content: 'Функции и их графики (линейные и квадратичные)', status: 'in_progress' },
    { title: 'Алгебра', content: 'Квадратные уравнения: дискриминант и его применение', status: 'in_progress' },
    { title: 'Алгебра', content: 'Системы уравнений (метод матриц)', status: 'in_progress' },
    { title: 'Алгебра', content: 'Рациональные функции и их графики', status: 'in_progress' },
    { title: 'Алгебра', content: 'Логарифмы: определение и свойства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Логарифмические уравнения и неравенства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Экспоненциальные функции и их графики', status: 'in_progress' },
    { title: 'Алгебра', content: 'Многочлены: деление и нахождение корней', status: 'in_progress' },
    { title: 'Алгебра', content: 'Векторы: операции и свойства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Тригонометрические функции: основные свойства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Матричная алгебра: операции с матрицами', status: 'in_progress' },
    { title: 'Алгебра', content: 'Определители и их свойства', status: 'in_progress' },
    { title: 'Алгебра', content: 'Системы линейных уравнений и матричные методы', status: 'in_progress' },
    { title: 'Алгебра', content: 'Функции: сложные функции и их графики', status: 'in_progress' },
    { title: 'Алгебра', content: 'Комплексные числа: операции и представления', status: 'in_progress' },
    { title: 'Алгебра', content: 'Абстрактная алгебра: группы, кольца и поля', status: 'in_progress' },
    { title: 'Алгебра', content: 'Линейная алгебра: пространство и линейные преобразования', status: 'in_progress' },
    { title: 'Алгебра', content: 'Дифференциальные уравнения: методы решения', status: 'in_progress' },
    { title: 'Алгебра', content: 'Теория чисел: основные понятия и теоремы', status: 'in_progress' },
    { title: 'Алгебра', content: 'Многочлены и их разложение', status: 'in_progress' },
    { title: 'Алгебра', content: 'Теория групп: основные определения и теоремы', status: 'in_progress' },
    { title: 'Алгебра', content: 'Кольца и поля: свойства и примеры', status: 'in_progress' },
    { title: 'Алгебра', content: 'Функциональный анализ: основные понятия', status: 'in_progress' },
    { title: 'Алгебра', content: 'Аналитическая геометрия в пространстве', status: 'in_progress' },
    { title: 'Алгебра', content: 'Теория матриц и линейные преобразования', status: 'in_progress' },







    { title: 'Геометрия', content: 'Основы геометрии: точки, линии, углы', status: 'in_progress' },
    { title: 'Геометрия', content: 'Плоские фигуры: треугольники и многоугольники', status: 'in_progress' },
    { title: 'Геометрия', content: 'Периметр и площадь плоских фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Симметрия и подобие фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Многоугольники и их свойства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Объемные фигуры: кубы, пирамиды, цилиндры', status: 'in_progress' },
    { title: 'Геометрия', content: 'Объем и площадь поверхности объемных фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Основы тригонометрии: синус, косинус, тангенс', status: 'in_progress' },
    { title: 'Геометрия', content: 'Прямоугольные треугольники и теорема Пифагора', status: 'in_progress' },
    { title: 'Геометрия', content: 'Параллельность и перпендикулярность прямых', status: 'in_progress' },
    { title: 'Геометрия', content: 'Аналитическая геометрия: координаты и уравнения прямых', status: 'in_progress' },
    { title: 'Геометрия', content: 'Стереометрия: прямые и плоскости в пространстве', status: 'in_progress' },
    { title: 'Геометрия', content: 'Конические сечения: окружности, эллипсы, параболы', status: 'in_progress' },
    { title: 'Геометрия', content: 'Основы векторной геометрии', status: 'in_progress' },
    { title: 'Геометрия', content: 'Тригонометрические функции и их графики', status: 'in_progress' },
    { title: 'Геометрия', content: 'Аналитическая геометрия в пространстве: плоскости и линии', status: 'in_progress' },
    { title: 'Геометрия', content: 'Многогранники и их свойства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Тригонометрические уравнения и неравенства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Решение задач на применение теорем и свойств фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Площади и объемы сложных фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Проективная геометрия: основные понятия', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрия на плоскости: комплексные числа и их применение', status: 'in_progress' },
    { title: 'Геометрия', content: 'Метрические свойства плоских фигур', status: 'in_progress' },
    { title: 'Геометрия', content: 'Преобразования плоскости: сдвиги, повороты', status: 'in_progress' },
    { title: 'Геометрия', content: 'Математическая модель и её применение', status: 'in_progress' },
    { title: 'Геометрия', content: 'Дифференциальная геометрия: кривизна и поверхности', status: 'in_progress' },
    { title: 'Геометрия', content: 'Фракталы и их свойства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Топология: основные понятия и теоремы', status: 'in_progress' },
    { title: 'Геометрия', content: 'Проблемы измерения и построения', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрические преобразования и их свойства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Анализ функций и их графиков', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрия многомерных пространств', status: 'in_progress' },
    { title: 'Геометрия', content: 'Проектирование и модели в геометрии', status: 'in_progress' },
    { title: 'Геометрия', content: 'Реальные приложения геометрии в науке и технике', status: 'in_progress' },
    { title: 'Геометрия', content: 'Разработка и исследование геометрических моделей', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрия Римана и Лобачевского', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрия многомерных пространств', status: 'in_progress' },
    { title: 'Геометрия', content: 'Геометрия на многообразиях', status: 'in_progress' },
    { title: 'Геометрия', content: 'Топологические пространства и их свойства', status: 'in_progress' },
    { title: 'Геометрия', content: 'Анализ на многообразиях', status: 'in_progress' },









    { title: 'Физика', content: 'Основы физики: предмет и методы', status: 'in_progress' },
    { title: 'Физика', content: 'Основные явления и законы механики', status: 'in_progress' },
    { title: 'Физика', content: 'Силы и их измерение', status: 'in_progress' },
    { title: 'Физика', content: 'Механические колебания и волны', status: 'in_progress' },
    { title: 'Физика', content: 'Тепловые явления и температурные шкалы', status: 'in_progress' },
    { title: 'Физика', content: 'Законы Ньютона и их применение', status: 'in_progress' },
    { title: 'Физика', content: 'Энергия и работа: основные понятия', status: 'in_progress' },
    { title: 'Физика', content: 'Кинетическая энергия и потенциальная энергия', status: 'in_progress' },
    { title: 'Физика', content: 'Механика жидкостей и газов: давление и объем', status: 'in_progress' },
    { title: 'Физика', content: 'Основы термодинамики: теплотехнические процессы', status: 'in_progress' },
    { title: 'Физика', content: 'Электрические явления: заряд и проводимость', status: 'in_progress' },
    { title: 'Физика', content: 'Основы электричества и магнетизма', status: 'in_progress' },
    { title: 'Физика', content: 'Электрические цепи и их анализ', status: 'in_progress' },
    { title: 'Физика', content: 'Оптика: преломление и отражение света', status: 'in_progress' },
    { title: 'Физика', content: 'Основы волновых явлений: звук и свет', status: 'in_progress' },
    { title: 'Физика', content: 'Электромагнитные явления: магнетизм и электромагнитные волны', status: 'in_progress' },
    { title: 'Физика', content: 'Тепловые явления: законы термодинамики', status: 'in_progress' },
    { title: 'Физика', content: 'Молекулярно-кинетическая теория: газовые законы', status: 'in_progress' },
    { title: 'Физика', content: 'Основы ядерной физики: радиация и реакции', status: 'in_progress' },
    { title: 'Физика', content: 'Физика атома: строение атома и спектры', status: 'in_progress' },
    { title: 'Физика', content: 'Классическая механика: законы сохранения', status: 'in_progress' },
    { title: 'Физика', content: 'Геометрическая и волновая оптика', status: 'in_progress' },
    { title: 'Физика', content: 'Основы квантовой физики: фотоэффект и двойственность', status: 'in_progress' },
    { title: 'Физика', content: 'Электромагнитные волны и их свойства', status: 'in_progress' },
    { title: 'Физика', content: 'Основы термодинамики: внутренние энергии и энтропия', status: 'in_progress' },
    { title: 'Физика', content: 'Электродинамика: законы Ома и Кирхгофа', status: 'in_progress' },
    { title: 'Физика', content: 'Квантовая механика: волновая функция и уравнение Шредингера', status: 'in_progress' },
    { title: 'Физика', content: 'Классическая и релятивистская механика', status: 'in_progress' },
    { title: 'Физика', content: 'Астрофизика и космология: основные концепции', status: 'in_progress' },
    { title: 'Физика', content: 'Новые материалы и их свойства', status: 'in_progress' },
    { title: 'Физика', content: 'Квантовая теория поля: основные идеи и приложения', status: 'in_progress' },
    { title: 'Физика', content: 'Современные представления о материи и энергии', status: 'in_progress' },
    { title: 'Физика', content: 'Экспериментальные методы в физике', status: 'in_progress' },
    { title: 'Физика', content: 'Нейронные сети и их физическое моделирование', status: 'in_progress' },
    { title: 'Физика', content: 'Теория относительности: специальная и общая', status: 'in_progress' },
    { title: 'Физика', content: 'Теория суперструн и ее физические следствия', status: 'in_progress' },
    { title: 'Физика', content: 'Астрономические наблюдения и их интерпретация', status: 'in_progress' },
    { title: 'Физика', content: 'Современные физические теории и их экспериментальное подтверждение', status: 'in_progress' },
    { title: 'Физика', content: 'Модели вселенной: от Большого взрыва до тепловой смерти', status: 'in_progress' },
    { title: 'Физика', content: 'Физика элементарных частиц: ускорители и детекторы', status: 'in_progress' },



    { title: 'Английский', content: 'Основы английского алфавита', status: 'in_progress' },
    { title: 'Английский', content: 'Простые фразы и выражения', status: 'in_progress' },
    { title: 'Английский', content: 'Времена Simple: Present, Past, Future', status: 'in_progress' },
    { title: 'Английский', content: 'Основные грамматические структуры', status: 'in_progress' },
    { title: 'Английский', content: 'Повседневная лексика и разговорные фразы', status: 'in_progress' },
    { title: 'Английский', content: 'Времена Continuous и Perfect', status: 'in_progress' },
    { title: 'Английский', content: 'Английская фонетика и произношение', status: 'in_progress' },
    { title: 'Английский', content: 'Условные предложения (Conditionals)', status: 'in_progress' },
    { title: 'Английский', content: 'Сложные предложения и союзные слова', status: 'in_progress' },
    { title: 'Английский', content: 'Чтение и понимание текстов средней сложности', status: 'in_progress' },
    { title: 'Английский', content: 'Современный английский язык: идиомы и фразовые глаголы', status: 'in_progress' },
    { title: 'Английский', content: 'Английский для профессиональных целей', status: 'in_progress' },
    { title: 'Английский', content: 'Анализ и интерпретация сложных текстов', status: 'in_progress' },
    { title: 'Английский', content: 'Письменные жанры: эссе, отчеты, деловая переписка', status: 'in_progress' },
    { title: 'Английский', content: 'Культура и идиомы англоговорящих стран', status: 'in_progress' },





    { title: 'Японский', content: 'Хирагана и катакана: основы письма', status: 'in_progress' },
    { title: 'Японский', content: 'Основные фразы и выражения', status: 'in_progress' },
    { title: 'Японский', content: 'Простые грамматические конструкции', status: 'in_progress' },
    { title: 'Японский', content: 'Основные иероглифы (кандзи)', status: 'in_progress' },
    { title: 'Японский', content: 'Чтение и понимание простых текстов', status: 'in_progress' },
    { title: 'Японский', content: 'Времена и формы глаголов', status: 'in_progress' },
    { title: 'Японский', content: 'Разговорные выражения и диалоги', status: 'in_progress' },
    { title: 'Японский', content: 'Сложные грамматические структуры и частички', status: 'in_progress' },
    { title: 'Японский', content: 'Кандзи: расширение словарного запаса', status: 'in_progress' },
    { title: 'Японский', content: 'Чтение и анализ сложных текстов', status: 'in_progress' },
    { title: 'Японский', content: 'Разговорные и письменные стили', status: 'in_progress' },
    { title: 'Японский', content: 'Культура и традиции Японии', status: 'in_progress' },
    { title: 'Японский', content: 'Перевод и интерпретация сложных текстов', status: 'in_progress' },
    { title: 'Японский', content: 'Официальная и деловая переписка', status: 'in_progress' },
    { title: 'Японский', content: 'Изучение современных тенденций и медиаматериалов', status: 'in_progress' },




    { title: 'Немецкий', content: 'Основы немецкого алфавита и произношения', status: 'in_progress' },
    { title: 'Немецкий', content: 'Простые фразы и выражения', status: 'in_progress' },
    { title: 'Немецкий', content: 'Времена Simple: Präsens, Präteritum, Futur I', status: 'in_progress' },
    { title: 'Немецкий', content: 'Основные грамматические правила', status: 'in_progress' },
    { title: 'Немецкий', content: 'Повседневная лексика и базовые темы', status: 'in_progress' },
    { title: 'Немецкий', content: 'Времена Perfect и Plusquamperfekt', status: 'in_progress' },
    { title: 'Немецкий', content: 'Сложные предложения и союзы', status: 'in_progress' },
    { title: 'Немецкий', content: 'Фонетика и произношение', status: 'in_progress' },
    { title: 'Немецкий', content: 'Чтение и понимание текстов средней сложности', status: 'in_progress' },
    { title: 'Немецкий', content: 'Разговорные выражения и идиомы', status: 'in_progress' },
    { title: 'Немецкий', content: 'Современный немецкий язык: идиомы и фразовые глаголы', status: 'in_progress' },
    { title: 'Немецкий', content: 'Анализ и интерпретация сложных текстов', status: 'in_progress' },
    { title: 'Немецкий', content: 'Письменные жанры: эссе, отчеты, деловая переписка', status: 'in_progress' },
    { title: 'Немецкий', content: 'Культура и традиции немецкоговорящих стран', status: 'in_progress' },
    { title: 'Немецкий', content: 'Немецкий для профессиональных целей', status: 'in_progress' },





    { title: 'Испанский', content: 'Основы испанского алфавита и произношения', status: 'in_progress' },
    { title: 'Испанский', content: 'Простые фразы и выражения', status: 'in_progress' },
    { title: 'Испанский', content: 'Времена Simple: Presente, Pretérito Perfecto, Futuro', status: 'in_progress' },
    { title: 'Испанский', content: 'Основные грамматические правила', status: 'in_progress' },
    { title: 'Испанский', content: 'Повседневная лексика и базовые темы', status: 'in_progress' },
    { title: 'Испанский', content: 'Времена Imperfecto и Pluscuamperfecto', status: 'in_progress' },
    { title: 'Испанский', content: 'Сложные предложения и союзы', status: 'in_progress' },
    { title: 'Испанский', content: 'Фонетика и произношение', status: 'in_progress' },
    { title: 'Испанский', content: 'Чтение и понимание текстов средней сложности', status: 'in_progress' },
    { title: 'Испанский', content: 'Разговорные выражения и идиомы', status: 'in_progress' },
    { title: 'Испанский', content: 'Современный испанский язык: идиомы и фразовые глаголы', status: 'in_progress' },
    { title: 'Испанский', content: 'Анализ и интерпретация сложных текстов', status: 'in_progress' },
    { title: 'Испанский', content: 'Письменные жанры: эссе, отчеты, деловая переписка', status: 'in_progress' },
    { title: 'Испанский', content: 'Культура и традиции испаноязычных стран', status: 'in_progress' },
    { title: 'Испанский', content: 'Испанский для профессиональных целей', status: 'in_progress' },






        { title: 'Иврит', content: 'Основы ивритского алфавита и произношения', status: 'in_progress' },
        { title: 'Иврит', content: 'Простые фразы и выражения', status: 'in_progress' },
        { title: 'Иврит', content: 'Основные грамматические конструкции', status: 'in_progress' },
        { title: 'Иврит', content: 'Основные слова и выражения', status: 'in_progress' },
        { title: 'Иврит', content: 'Чтение и понимание простых текстов', status: 'in_progress' },
        { title: 'Иврит', content: 'Времена и формы глаголов', status: 'in_progress' },
        { title: 'Иврит', content: 'Разговорные выражения и диалоги', status: 'in_progress' },
        { title: 'Иврит', content: 'Сложные грамматические структуры', status: 'in_progress' },
        { title: 'Иврит', content: 'Чтение и анализ сложных текстов', status: 'in_progress' },
        { title: 'Иврит', content: 'Фразеология и идиомы', status: 'in_progress' },
        { title: 'Иврит', content: 'Современный иврит: идиомы и фразовые глаголы', status: 'in_progress' },
        { title: 'Иврит', content: 'Анализ и интерпретация сложных текстов', status: 'in_progress' },
        { title: 'Иврит', content: 'Письменные жанры: эссе, отчеты, деловая переписка', status: 'in_progress' },
        { title: 'Иврит', content: 'Культура и традиции Израиля', status: 'in_progress' },
        { title: 'Иврит', content: 'Иврит для профессиональных целей', status: 'in_progress' },

            { title: 'MySQL', content: 'Основы SQL: SELECT, INSERT, UPDATE, DELETE', status: 'in_progress' },
            { title: 'MySQL', content: 'Создание и управление базами данных и таблицами', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с типами данных (INT, VARCHAR, DATE, и т.д.)', status: 'in_progress' },
            { title: 'MySQL', content: 'Основы индексов и их использование', status: 'in_progress' },
            { title: 'MySQL', content: 'Основные функции и операторы SQL', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с NULL значениями', status: 'in_progress' },
            { title: 'MySQL', content: 'Пользовательские функции и выражения', status: 'in_progress' },
            { title: 'MySQL', content: 'Создание и использование представлений (views)', status: 'in_progress' },
            { title: 'MySQL', content: 'Транзакции и управление транзакциями', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с хранимыми процедурами и функциями', status: 'in_progress' },
            { title: 'MySQL', content: 'Оптимизация запросов и индексов', status: 'in_progress' },
            { title: 'MySQL', content: 'Репликация и резервное копирование баз данных', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с транзакциями и блокировками', status: 'in_progress' },
            { title: 'MySQL', content: 'Кластеризация и распределенные базы данных', status: 'in_progress' },
            { title: 'MySQL', content: 'Использование внешних ключей и целостности данных', status: 'in_progress' },
            { title: 'MySQL', content: 'Полнотекстовый поиск и полнотекстовые индексы', status: 'in_progress' },
            { title: 'MySQL', content: 'Параллельные запросы и производительность', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с JSON в MySQL', status: 'in_progress' },
            { title: 'MySQL', content: 'Оптимизация серверных настроек и конфигурация', status: 'in_progress' },
            { title: 'MySQL', content: 'Масштабирование и высокодоступные решения', status: 'in_progress' },
            { title: 'MySQL', content: 'Использование MySQL в больших данных и аналитике', status: 'in_progress' },
            { title: 'MySQL', content: 'Управление пользователями и правами доступа', status: 'in_progress' },
            { title: 'MySQL', content: 'Разработка и тестирование MySQL приложений', status: 'in_progress' },
            { title: 'MySQL', content: 'Работа с временными таблицами и индексами', status: 'in_progress' },
            { title: 'MySQL', content: 'Секреты и рекомендации по безопасности MySQL', status: 'in_progress' },


            { title: 'Redis', content: 'Основы Redis: установка и настройка', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с основными структурами данных: строки, списки, множества', status: 'in_progress' },
            { title: 'Redis', content: 'Команды и операции: SET, GET, LPUSH, SADD', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с ключами и сроками действия ключей', status: 'in_progress' },
            { title: 'Redis', content: 'Основы транзакций и пайплайнинга', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с базовыми командами и скриптами', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с репликацией и конфигурацией мастера-слейва', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с хэшами и отсортированными множествами', status: 'in_progress' },
            { title: 'Redis', content: 'Репликация и настройка кластеров', status: 'in_progress' },
            { title: 'Redis', content: 'Использование Redis Pub/Sub для сообщений', status: 'in_progress' },
            { title: 'Redis', content: 'Оптимизация производительности и управление памятью', status: 'in_progress' },
            { title: 'Redis', content: 'Анализ и мониторинг Redis', status: 'in_progress' },
            { title: 'Redis', content: 'Использование Lua скриптов и их применение', status: 'in_progress' },
            { title: 'Redis', content: 'Работа с Redis Streams и их применение', status: 'in_progress' },
            { title: 'Redis', content: 'Настройка и использование Redis Sentinel', status: 'in_progress' },
            { title: 'Redis', content: 'Разработка и настройка Redis Modules', status: 'in_progress' },
            { title: 'Redis', content: 'Обеспечение отказоустойчивости и резервного копирования', status: 'in_progress' },
            { title: 'Redis', content: 'Интеграция Redis с другими системами и приложениями', status: 'in_progress' },
            { title: 'Redis', content: 'Современные подходы к масштабированию и распределению нагрузки', status: 'in_progress' },
            { title: 'Redis', content: 'Интерфейсы и API для расширенной работы с Redis', status: 'in_progress' },
            { title: 'Redis', content: 'Разработка высокопроизводительных приложений на Redis', status: 'in_progress' },
            { title: 'Redis', content: 'Анализ и оптимизация Redis в условиях высоких нагрузок', status: 'in_progress' },
            { title: 'Redis', content: 'Использование Redis для различных сценариев кэширования', status: 'in_progress' },
            { title: 'Redis', content: 'Управление большими объемами данных в Redis', status: 'in_progress' },
            { title: 'Redis', content: 'Практики и подходы к масштабированию Redis в облаке', status: 'in_progress' },



            { title: 'Elasticsearch', content: 'Основы Elasticsearch: установка и настройка', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Основы индексации и поиска', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Работа с JSON-документами', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Основные запросы и фильтры', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Настройка и использование аналитики и агрегаций', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Использование и настройка шаблонов индексов', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Работа с настройками индекса и маппингом', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Работа с репликацией и шардированием', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Оптимизация запросов и использование кэша', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Интеграция Elasticsearch с Kibana и Logstash', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Работа с Elasticsearch API и инструментами командной строки', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Настройка и использование Elastic Stack для мониторинга и визуализации', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Анализ и мониторинг производительности кластера', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Разработка и тестирование сложных запросов и фильтров', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Настройка и использование Elasticsearch Security', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Разработка плагинов и расширений для Elasticsearch', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Масштабирование и управление кластерами Elasticsearch', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Продвинутые техники агрегации и анализа данных', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Интеграция Elasticsearch с другими системами и платформами', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Работа с большими объемами данных и оптимизация производительности', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Практические рекомендации по настройке и эксплуатации Elasticsearch', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Использование и настройка Elasticsearch для специальных приложений и сценариев', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Управление безопасностью и доступом в Elasticsearch', status: 'in_progress' },
            { title: 'Elasticsearch', content: 'Передовые практики и тренды в использовании Elasticsearch', status: 'in_progress' }
        
    




];


let lessonsHtml = '<div>';
const mainElement = document.querySelector('main');

lessons.forEach(lesson => {
    lessonsHtml += `
        <div class='lesson ${lesson.status}'>
            <h3>${lesson.title}</h3>
            <p>${lesson.content}</p>
        </div>
    `
});

lessonsHtml += '</div>';
mainElement.innerHTML = lessonsHtml;